AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Build AWS Golang Lambda function to update the DynamoDB, triggered by events from EventBridge.

Parameters:
  Environment:
    Type: String
    Description: The runtime environment of this stack

Resources:
  EventBridgeResource:
    Type: AWS::Events::EventBus
    Properties: 
      Name: !Sub evb-resource-${Environment}

  EventsDDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub evb-events-table-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "eventId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "eventId"
          KeyType: "HASH"    

  EventsToDDBLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Updates EventBridge events to DynamoDB table"
      CodeUri: ../lambdas/update-events
      Handler: update-events
      Runtime: go1.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Tracing: Active
      Environment:
        Variables:
          EVENTS_DDB_TABLE: !Ref EventsDDBTable

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Policies:
        - PolicyName: WriteAccessToDDB
          PolicyDocument:
            Statement:
              - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource:
                - !GetAtt EventsDDBTable.Arn

  PermissionEvbToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt EventsToDDBLambda.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com    
  
  
  # Rule to route incoming events to EventsDDBLambda    
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !GetAtt EventBridgeResource.Name
      Description: "Route Events of type storeToDDB to eventsToDDBLambda"
      EventPattern:
        detail-type:
          - "StoreToDDB"
      State: ENABLED
      Targets:
        - Id: EventHandlingLambda
          Arn: !GetAtt EventsToDDBLambda.Arn
