AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Build AWS Golang Lambda function to update the DynamoDB, triggered by events from EventBridge.

Parameters:
  Environment:
    Type: String
    Description: The runtime environment of this stack

Resources:
  EventBridgeResource:
    Type: AWS::Events::EventBus
    Properties: 
      Name: !Sub evb-resource-${Environment}

